.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\"
.TH PG_EXEC 1 "October 2003" "Debian Project" "Debian Linux"
.SH NAME
pg_exec \- Wrapper program to execute PostgreSQL commands
.SH SYNOPSIS
.BR pg_exec " [" -v
.IR version ]
.RB [ -h
.IR remotehost ] " command " [ command_options ]
.P
.B pg_exec -v
.IB version " -c " cluster
.BR "pg_dump " | " pg_dumpall"
.RI [ command_options ]
.SH OPTIONS
.TP
.BI -c " cluster"
Used only if 
.I command
is
.BR pg_dump " or " pg_dumpall .
Specify the cluster in which
.I command
should be run.
.TP
.BI -v " version"
When connecting to a remote host, specify the version of the PostgreSQL
software to which you are connecting.  If
.B -v
is not specified, the latest available version will be used.

.SH DESCRIPTION
.P
.B pg_exec
is used either with the
.B -h
option, or with a remote host specified in $PGHOST, and executes the
specified command using the
version of the PostgreSQL software specified by
.B -v
.IR version .
If none is specified, the latest available version is used.
.P
The program checks the command options of the command being run to ensure
that any host given there does not resolve to a local hostname and does not
contradict the host given with the 
.B -h
option to
.BR pg_exec .
.P
Since
.B pg_dump
has substantially improved from version to version and now has the
capability of reading older database formats, the
.B -c
option may be used with
.B -v
to specify a later version of
.B pg_dump
to use on the specified cluster on the local machine.  (This is an exception
to the rule that
.B pg_exec
can only run programs on remote machines.)  This is particularly useful
for doing database upgrades.  It is not recommended for making dumps that
are to be read back into the same version of the database.
.SH FILES
.TP
.I /etc/postgresql-common/user_clusters 
contains the default cluster and database for users and groups as set by
the administrators.
.TP
.I $HOME/.postgresqlrc
contains defaults set by the user himself.  It overrides 
.I /etc/postgresql-common/user_clusters
unless the administrator has set the FORCED flag in that file.
.SH SEE ALSO
.BR pg_default (1),
.BR pg_wrapper (1)
.SH AUTHOR
Oliver Elphick <Oliver.Elphick@lfix.co.uk>
