#!/bin/sh
set -e

# install locales; this happens differently on Debian and Ubuntu
if [ -e /etc/locale.gen ]; then
    # Debian
    while read locale ; do
	if ! grep -q "^$locale\$" /etc/locale.gen ; then
	    echo "$locale" >> /etc/locale.gen
	    run=1
	fi
    done <<-EOF
	en_US.UTF-8 UTF-8
	ru_RU ISO-8859-5
	ru_RU.UTF-8 UTF-8
EOF
    [ "$run" ] && locale-gen
else
    # Ubuntu
    # locale-gen will skip existing locales, so just call it for all here
    locale-gen en_US.UTF-8 ru_RU ru_RU.UTF-8
fi

cd /usr/share/postgresql-common
# autopkgtest considers everything on stderr to be an error, redirect to stdout here
env -u TMPDIR -u LC_ALL LANG=en_US.utf8 ./testsuite 2>&1
