.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\"
.TH CLUSTER_PORTS 5 "November 2003" "Debian Project" "Debian Linux"
.SH NAME
cluster_ports \- File linking PostgreSQL clusters to ports
.SH DESCRIPTION
.P
This file maps PostgreSQL database clusters against their database
versions, the ports on which their postmasters are to listen, the Unix
logins of their administrators and the directories where their data are
to be found.
.SH FORMAT
.P
Comments are introduced by the character
.BR # .
Comments may follow data on a line; the first comment character terminates
the data.
Leading whitespace and blank lines are ignored.
.P
Each uncommented, non-blank line describes a cluster.
.P
Fields must be given in the following order, separated by whitespace:
.TP
.B CLUSTER
The name of the cluster; this must be unique in this file.
.TP
.B STATUS
.IP ""
.RB "'" active "'"
if a postmaster should be started at boot time;
.IP ""
.RB "'" inactive "'"
if it can only be started by the administrator;
.IP ""
.RB "'" upgrading "'"
only when the database is being upgraded from
one major version to another - an 'upgrading' database is
inaccessible except to the administrator;
.IP ""
.RB "'" failed-upgrade "'"
if an upgrade failed.
.TP
.B OWNER
The Unix login of the cluster owner and administrator.  This must not
be
.BR root .
.TP
.B VERSION
The database version of the cluster.  This value should be the same as
that recorded in $PGDATA/PG_VERSION.  It is required here in case the
wrapper program should not have the permissions to read that file.
.TP
.B PORT
The port on which this cluster's postmaster should listen;
ports 5430 and 5431 are reserved for cluster upgrades.
The cluster whose postmaster listens on port 5432 is the default cluster
for any user who does not match any line in 
.IR user_clusters .
.TP
.B CLUSTERPATH
The pathname of the directory containing the data directory for this cluster.
.SH NOTES
This file will be altered by initdb (when run by root or postgres)
which will add lines when a new cluster is created. 
.B pg_version_upgrade
will change the active flag to 
.B upgrading
while an upgrade is taking place.
.P
If you wish to edit this file to change the port numbers
attached to clusters, you must use 
.B /etc/init.d/postgresql stop
to stop all the postmasters.  If you do not, from the time you file
your changes, the postmasters will still be listening on the old ports
but users connecting though this system will be connecting to the new
ports.  Users will not be pleased with you...
.P
Use 
.B /etc/init.d/postgresql start
when you have filed your changes.
.SH EXAMPLE
# CLUSTER    STATUS    USER      PORT  CLUSTERPATH
.PD 0
.P
postgresql   active    postgres  5432  /var/lib/postgres/db    # 7.3
.P
developers   inactive  postgres  5433  /var/lib/postgres/devel # 7.4
.P
mycustomer01 active    cust01    5436  /usr3/cust/cust01       # 7.3
.PD
.SH SEE ALSO
.BR pg_wrapper (1),
.BR user_clusters (5)
.SH AUTHOR
Oliver Elphick
.RI < olly@lfix.co.uk >
