#!/usr/bin/perl -w
#
#  pg_ctl_common 
#
#  Script to start multiple PostgreSQL postmasters according to the
#  configuration
#

my $ix = 0;
my $action = "";
my $cluster;

print @ARGV,"\n";

if ( $ARGV[0] eq "-c" ) {
	$cluster = $ARGV[1];
	$ix = 2;
}

die "You must run pg_ctl_common as root\n" unless $UID == 0;

$action = $ARGV[$ix++];

if ($action eq "start" || $action eq "reload" || $action eq "status") {
	print "Action = $action\n";
} elsif ($action eq "stop" || $action eq "restart") {
	if ($ARGV[$ix++] eq "-m") {
		$mode = $ARGV[$ix];
	} else {
		$mode = "fast";
	}
	print "Action = $action; mode = $mode\n";
} else {
	print "Syntax: pg_ctl_common [-c cluster] start|stop|restart|reload|status\n";
	exit 1;
}

my ($clname, $status, $owner, $version, $port, $path);

# delete this and the next line and uncomment the line after
my $portfile = "/tmp/cluster_ports";
# my $portfile = "/etc/postgresql/cluster_ports";
open CLUSTER_PORTS, $portfile or die "Cannot open $portfile";

while (<CLUSTER_PORTS>) {
	if (! m/^\s*(#.*|)$/) {
		($clname, $status, $owner, $version, $port, $path) = split /\s\s*/, $_;
		printf "Cluster: %s; Status: %s; Owner: %s; Version: %s; Port: %s; Path: %s\n", $clname, $status, $owner, $version, $port, $path;
		if (! defined $cluster || $cluster eq $clname) {
			# set effective uid to cluster owner
			my ($name, $passwd, $uid, $gid, $quota, $comment, $gcos, $dir, $shell) = getpwnam $owner;
			die "Cluster $cluster's owner is set to root, which is not allowed\n" if $uid == 0;
			$EUID = $uid;
			
			# check cluster database path and version
			my $version_file = "$path/PG_VERSION";
			open PGVERSION, $version_file or die "Could not open $version_file\n";
			read PGVERSION, $dbver, 999 or die "Could not read from $version_file";
			close PGVERSION;
			chomp $dbver;
			die "Cluster $cluster specifies Pg version $version, but actual version is $dbver\n" unless $version == $dbver;

			# set correct port to listen on
			$ENV{PGPORT} = $port;

			# define the command to run
			$cmd = "/usr/lib/postgresql/$version/bin/pg_ctl -D $path";
			if (action eq "start") {
				$options = "-p /usr/lib/postgresql/$version/bin/postmaster ";
			} elsif ($action eq "stop" || $action eq "restart") {
				$options = "-m $mode";
			}
			print "Running command: $cmd $options\n";
			system("$cmd $options");
			$EUID = 0;
		}
	}
}
