.TH pg_createcluster 8 "January 01, 2005" "Martin Pitt"

.SH NAME
pg_createcluster \- create a new PostgreSQL cluster

.SH SYNOPSIS
.B pg_createcluster
.I version clustername

.SH DESCRIPTION
.B pg_createcluster 
creates a new PostgreSQL server cluster (i. e. a
collection of databases served by a postmaster instance) and
integrates it into the multi\-version/multi\-cluster architecture of the
.B postgresql\-common
package. 

Given a major PostgreSQL
.I version
(like "7.4" or "8.0") and a
.I clustername
(which must be unique for all clusters of one particular version), it
creates the necessary configuration files in
.B /etc/postgresql/\fIversion\fB/\fIclustername\fB/\fR;
in particular these are postgresql.conf, pg_ident.conf, pg_hba.conf,
and a symbolic link "pgdata" which points to the actual data
directory. 

By default, the data directory is
.B /var/lib/postgresql/\fIversion\fB/\fIclustername\fB/\fR. If it does
not yet exists, PostgreSQL's
.B initdb 
command is used to generate a new cluster structure.
If the data directory already exists, it is integrated into the
.B postgresql\-common
structure by moving the configuration file and creating the pgdata
link.

.SH SEE ALSO
.BR pg_startcluster (8),
.BR pg_stopcluster (8),
.BR pg_reloadcluster (8),
.BR pg_lsclusters (1),
.BR pg_wrapper (1)

.SH AUTHOR
Martin Pitt <mpitt@debian.org>
