.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\"
.TH PG_DEFAULT 1 "October 2003" "Debian Project" "Debian Linux"
.SH NAME
pg_default \- Sets cluster and database for PostgreSQL commands
.SH SYNOPSIS
.P
.B pg_default
.BR -a " | "
.BI -u " user "
.RB "| " -g
.I " group"
.RB [ -f ]
.BI -c " cluster"
[
.BI -d " database"
]
.P
.B pg_default
[
.BI -c " cluster"
[
.BI -d " database"
]] | [-V]
.SH OPTIONS
.TP
.BI -u " user"
Specify the Unix login for which the defaults are to be set.  
This option may be used only by root or the administrator.
.TP
.BI -g " group"
Specify the Unix group for which the defaults are to be set. 
This option may be used only by root or the administrator.
.TP
.B -a
Specify the default choice for all users, that will apply if no more
specific match of user or group is found.
This option may be used only by root or the administrator.
.TP
.B -f
Set the FORCED flag in
.IR user_clusters ,
so that the user is unable to override the choice made for him.
This option may be used only by root or the administrator.
.TP
.BI -c " cluster"
Specify the name of the cluster (in 
.IR cluster_ports )
to which the user should connect by default when a PostgreSQL command is run.
.TP
.BI -d " database"
Specify the name of the database within the specified cluster to which the
user should connect by default.  If
.I database
is *, the connection will be to a database whose name is the same as the
user's login.
.TP
.B -V
When
.B pg_default
is used to report the current settings, this option makes
it report the default system settings as well as the user's own settings,
or it reports that the system settings cannot be overridden.
.SH DESCRIPTION
.P
When 
.B pg_default
is run with no options, it reports the default database
and cluster for the current user.
If
.B -c
is specified,
.B pg_default
sets the PostgreSQL cluster for a user, and the database too, if
.B -d
is also given.
.P
The superuser (root) or the PostgreSQL administrator (postgres) may
use the 
.B -u
and
.B -g
options to set the defaults for another user and the 
.B -a
option to set the default cluster and database.
The 
.B -f
option is used to set the FORCED flag in
.IR user_clusters ,
so that the user
is not permitted to override the administrator's choices for him.
.P
Other users can set only their own options, which are stored in
.IR ~/.postgresqlrc .
.SH FILES
.TP
.I /etc/postgresql-common/user_clusters 
stores the default cluster and database for users and groups as set by
the administrators.  By setting the FORCED flag for a user or group, it
is possible for an administrator to override a
user's choices so that the user can connect only to the cluster and
database selected for him.
.TP
.I $HOME/.postgresqlrc
stores defaults set by the user himself.
.SH BUGS
The FORCED flag is meant to protect naive users from stupid mistakes.  It
is not a security measure, since it can easily be bypassed by entering the
desired pathname and setting PGPORT directly.
.SH SEE ALSO
.BR pg_exec (1),
.BR pg_wrapper (1)
.SH AUTHOR
Oliver Elphick <olly@lfix.co.uk>
