#!/usr/bin/perl
# Show all PostgreSQL clusters in a list
#
# (C) 2005 Martin Pitt <mpitt@debian.org>

use lib '/usr/share/postgresql-common';
use PgCommon;

$show_header = 1;

@columns = ('Version', 'Cluster', 'Port', 'Status', 'Owner', 'Data directory',
            'Log file');
@colwidths = qw/8 10 5 7 9 35 30/;

foreach $cw (@colwidths) {
    $fmtstring .= '%-'.$cw.'s';
}
$fmtstring .= "\n";

printf $fmtstring, @columns;

foreach $v (get_versions) {
    foreach $c (get_version_clusters $v) {
        %info = cluster_info $v, $c;
        printf $fmtstring, ($v, $c, $info{'port'}, 
            $info{'running'} ? "online" : "down", 
            (getpwuid $info{'owneruid'})[0], $info{'pgdata'},
            $info{'logfile'});
    }
}
