#!/usr/bin/perl
# Show all PostgreSQL clusters in a list
#
# (C) 2005 Martin Pitt <mpitt@debian.org>

use lib '/usr/share/postgresql-common';
use PgCommon;

$show_header = 1;

print "Version\tCluster\tPort\tStatus\tData directory\n" if $show_header;

foreach $v (get_versions) {
    foreach $c (get_version_clusters $v) {
        %info = cluster_info $v, $c;
        print join "\t", ($v, $c, $info{'port'}, $info{'running'} ? "running" :
        "down", $info{'pgdata'}), "\n";
    }
}
