#!/bin/sh -e

# reload cluster $2 of version $1

if [ -z "$1" -o -z "$2" ]; then
    echo "Usage: $0 <version> <cluster>" >&2
    exit 1
fi

. /usr/share/postgresql-common/init.d-functions

prepare_cluster "$1" "$2"

start-stop-daemon --chuid postgres --start --exec "$PG_CTL" -- -D "$PGDATA" -s reload

