#!/usr/bin/perl -w
# Call a PostgreSQL client program with the version, cluster and default
# database specified in ~/.postgresqlrc or
# /etc/postgresql-common/user_clusters.
#
# (C) 2005 Martin Pitt <mpitt@debian.org>

use lib '/usr/share/postgresql-common';
use PgCommon;

@commands = qw/clusterdb createdb createlang createuser dropdb droplang dropuser pg_dump
    pg_dumpall pg_restore psql vacuumdb vacuumlo/;

$cmd = (split '/', $0)[-1];
grep { $cmd eq $_ } @commands or die "pg_wrapper: invalid command name $cmd";

# Determine $version, $cluster, $db, $port
($version, $cluster, $db) = user_cluster_map();
if ($version && $cluster) {
    $port = (get_conf_value $version, $cluster, 'port');
} else {
    $version = "8.0"; # TODO: determine version from default port
}

#print "pg_wrapper debug: version $version, cluster $cluster, port $port, db $db\n";

$ENV{'PGPORT'} = "$port" if $port;
$ENV{'PGHOST'} = $PgCommon::socketdir;
$ENV{'PGDATABASE'} = $db if $db;

@args = (get_program_path ($cmd, $version));
push @args, @ARGV;
exec @args;

