.\" Hey, Emacs!  This is an -*- nroff -*- source file.
.\"
.TH PG_WRAPPER 1 "October 2003" "Debian Project" "Debian Linux"
.SH NAME
pg_wrapper \- Wrapper program for PostgreSQL commands
.SH DESCRIPTION
.P
This program is run only as a link to names
which correspond to PostgreSQL programs in 
.RI /usr/lib/postgresql/ version /bin.
If the specified host is the local machine, it finds the correct
cluster and database for the user and calls
the correct version of the desired program to connect to that cluster and
database, supplying any specifed options to that command.
.P
If a remote host is specified,
.B pg_wrapper
behaves like
.B pg_exec.
.SH FILES
.TP
.I /etc/postgresql/user_clusters 
stores the default cluster and database for users and groups as set by
the administrators.  By setting the FORCED flag for a user or group, it
is possible for an administrator to override a
user's choices so that the user can connect only to the cluster and
database selected for him.
.TP
.I $HOME/.postgresqlrc
stores defaults set by the user himself.

.SH SEE ALSO
.BR pg_default (1),
.BR pg_exec (1)
.SH AUTHOR
Oliver Elphick <olly@lfix.co.uk>
