.debian_script: &debian_script
  - $SUDO apt-get update
  - $SUDO apt-get -o DPkg::Options::=--force-confnew dist-upgrade -y
  - $SUDO apt-get install -y build-essential fakeroot debhelper libreadline-dev lsb-release dh-systemd
  - rm -f ../*.deb ../*.dsc ../*.buildinfo ../*.changes ../*.tar.*
  - dpkg-buildpackage -uc -us -rfakeroot
  - ( set -x; for deb in ../*.deb; do dpkg-deb --info $deb; dpkg-deb --contents $deb; done )
  - ( set -x; $SUDO dpkg --force-confmiss --force-confnew -i ../*.deb || { $SUDO apt-get install -fy; $SUDO dpkg --force-confmiss --force-confnew -i ../*.deb; } )
  - dpkg -l postgresql\* | cat
  - $SUDO ./cleanpg
  - cd /usr/share/postgresql-common && $SUDO ./testsuite -v "$(./supported-versions)" -i

sid:
  image: debian:unstable
  script: *debian_script
  variables:
    SKIP_IPV6: 1

buster:
  tags:
    - buster
  script: *debian_script
  variables:
    SUDO: sudo

stretch:
  tags:
    - stretch
  script: *debian_script
  variables:
    SUDO: sudo

centos7:
  tags:
    - centos7
  script:
    - sudo yum install -y rpm-build
    - make rpmremove
    - make rpmbuild
    - rpm -ql pgdg-redhat-repo > /dev/null || sudo yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    - sudo yum -y update
    - make rpminstall
    - sudo ./cleanpg
    - cd /usr/share/postgresql-common && sudo ./testsuite -v "$(./supported-versions)" -i
