#!/usr/bin/perl -wT
# Show all PostgreSQL clusters in a list
#
# (C) 2005 Martin Pitt <mpitt@debian.org>

use lib '/usr/share/postgresql-common';
use PgCommon;
use Getopt::Long;

exit 1 unless GetOptions ('h|no-header' => \$no_header);

@columns = ('Version', 'Cluster', 'Port', 'Status', 'Owner', 'Data directory',
            'Log file');
@colwidths = qw/7 9 4 6 8 34 30/;

foreach $cw (@colwidths) {
    $fmtstring .= '%-'.$cw.'s ';
}
$fmtstring .= "\n";

printf $fmtstring, @columns unless $no_header;

foreach $v (sort (get_versions())) {
    my @clusters = get_version_clusters $v;
    foreach $c (sort @clusters) {
        %info = cluster_info $v, $c;
        printf $fmtstring, ($v, $c, $info{'port'}, 
            $info{'running'} ? "online" : "down", 
            (getpwuid $info{'owneruid'})[0], $info{'pgdata'},
            $info{'logfile'});
    }
}

__END__

=head1 NAME

pg_lsclusters - show information about all PostgreSQL clusters

=head1 SYNOPSIS

B<pg_lsclusters> [I<options>]

=head1 DESCRIPTION

This command shows a list about the configuration and status of all clusters.

=head1 OPTIONS

=over 4

=item B<-h>, B<--no-header>

Do not print the column header line.

=head1 AUTHOR

Martin Pitt L<E<lt>mpitt@debian.orgE<gt>>
